name: Build Website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setting timezone
        run: sudo timedatectl set-timezone America/New_York
      - name: Install packages
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Install netlify tools
        run: pnpm install -g netlify-cli
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
